# Generated by Django 4.2.5 on 2023-10-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easysign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_api_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
